# Generated by Django 5.1.5 on 2025-01-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authuser", "0004_alter_followers_follower_alter_followers_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followers",
            name="follower",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="followers",
            name="user",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="likepost",
            name="post_id",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="likepost",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
