# Generated by Django 5.1.5 on 2025-01-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authuser", "0010_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profileimg",
            field=models.ImageField(
                blank=True,
                default="blank-profile-picture.png",
                null=True,
                upload_to="profile_images",
            ),
        ),
    ]
