# Generated by Django 5.1.5 on 2025-01-31 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authuser", "0011_alter_profile_profileimg"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user_profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="authuser.profile",
            ),
            preserve_default=False,
        ),
    ]
