# Generated by Django 5.1.5 on 2025-01-31 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authuser", "0012_comment_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="user_profile",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authuser.profile",
            ),
        ),
    ]
