# Generated by Django 5.1.5 on 2025-02-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authuser", "0014_rename_user_profile_comment_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="likepost",
            name="liked",
            field=models.BooleanField(default=False),
        ),
    ]
