# Generated by Django 5.1.5 on 2025-03-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authuser", "0016_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="comment_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
